export const GET_LAST_JOURNAL = 'index/get_last_journal'
export const GET_PREVORNEXT_JOURNAL = 'index/get_prev_or_next_journal'
export const CHANGE_TAP_INFO = 'index/change_tap_info'
export const PLAY_OR_STOP_MUSIC = 'index/play_or_stop_music'
export const LOAC_CURRENT_MUSIC = 'index/lock_current_music'
export const MUSIC_OVER = 'index/music_over'
export const LEAVE_JOURNAL = 'index/leave_journal' 